"""
IT Ticket Routing & Priority Prediction — Streamlit App
Run:  streamlit run app.py
Requires: models.pkl in the same directory (generated by the Jupyter notebook)
"""

import streamlit as st
import pickle
import numpy as np
import time

# ── Page config ───────────────────────────────────────────────
st.set_page_config(
    page_title="IT Ticket AI",
    page_icon="🎫",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Custom CSS ────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&family=DM+Mono&display=swap');

html, body, [class*="css"] {
    font-family: 'DM Sans', sans-serif;
}

/* ── sidebar ── */
[data-testid="stSidebar"] {
    background: #0f1117;
    border-right: 1px solid #1e2130;
}
[data-testid="stSidebar"] * { color: #e2e8f0 !important; }
[data-testid="stSidebar"] .stTextArea textarea {
    background: #1a1f2e !important;
    border: 1px solid #2d3452 !important;
    color: #e2e8f0 !important;
    font-family: 'DM Mono', monospace !important;
    font-size: 13px !important;
    border-radius: 8px !important;
}
[data-testid="stSidebar"] .stButton button {
    background: linear-gradient(135deg, #4F46E5, #7C3AED) !important;
    color: white !important;
    border: none !important;
    border-radius: 8px !important;
    font-weight: 600 !important;
    padding: 0.6rem 1.4rem !important;
    width: 100% !important;
    font-size: 15px !important;
    transition: opacity 0.2s !important;
}
[data-testid="stSidebar"] .stButton button:hover { opacity: 0.88 !important; }

/* ── main area ── */
.block-container { padding-top: 1.5rem !important; max-width: 1100px !important; }

/* Metric cards */
.metric-card {
    background: #ffffff;
    border: 1px solid #e8ecf4;
    border-radius: 14px;
    padding: 1.2rem 1.4rem;
    text-align: center;
    box-shadow: 0 2px 8px rgba(0,0,0,0.04);
}
.metric-card .label {
    font-size: 12px;
    color: #64748b;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    margin-bottom: 4px;
}
.metric-card .value {
    font-size: 28px;
    font-weight: 600;
    color: #1e293b;
    line-height: 1.1;
}
.metric-card .sub {
    font-size: 12px;
    color: #94a3b8;
    margin-top: 2px;
}

/* Result cards */
.result-card {
    background: #ffffff;
    border: 1px solid #e8ecf4;
    border-radius: 16px;
    padding: 1.4rem 1.6rem;
    margin-bottom: 1rem;
    box-shadow: 0 2px 12px rgba(0,0,0,0.04);
}
.result-card h4 {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #94a3b8;
    margin: 0 0 8px;
}
.result-main {
    font-size: 20px;
    font-weight: 600;
    color: #1e293b;
    margin-bottom: 4px;
}
.confidence-badge {
    display: inline-block;
    font-size: 12px;
    font-weight: 500;
    padding: 2px 10px;
    border-radius: 99px;
}
.conf-high   { background: #dcfce7; color: #166534; }
.conf-medium { background: #fef9c3; color: #854d0e; }
.conf-low    { background: #fee2e2; color: #991b1b; }

/* Priority badge */
.prio-high   { background: #fee2e2; color: #991b1b; padding: 4px 14px; border-radius: 99px; font-weight: 600; font-size: 15px; }
.prio-medium { background: #fef9c3; color: #854d0e; padding: 4px 14px; border-radius: 99px; font-weight: 600; font-size: 15px; }
.prio-low    { background: #dcfce7; color: #166534; padding: 4px 14px; border-radius: 99px; font-weight: 600; font-size: 15px; }

/* Tags */
.tag-chip {
    display: inline-block;
    background: #f1f5f9;
    color: #475569;
    font-size: 12px;
    font-weight: 500;
    padding: 4px 12px;
    border-radius: 99px;
    margin: 3px 3px 3px 0;
    border: 1px solid #e2e8f0;
}

/* Progress bar override */
.stProgress > div > div > div { background: #4F46E5 !important; }

/* Section header */
.section-header {
    font-size: 13px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: #94a3b8;
    padding: 0 0 6px;
    border-bottom: 1px solid #f1f5f9;
    margin-bottom: 1rem;
}

/* Top-dept table */
.dept-row {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 8px;
}
.dept-name { font-size: 13px; color: #334155; min-width: 200px; }
.dept-bar-track {
    flex: 1;
    height: 6px;
    background: #f1f5f9;
    border-radius: 3px;
    overflow: hidden;
}
.dept-bar-fill { height: 100%; background: #4F46E5; border-radius: 3px; }
.dept-pct { font-size: 12px; color: #94a3b8; min-width: 42px; text-align: right; }

/* History item */
.hist-item {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 10px;
    padding: 0.8rem 1rem;
    margin-bottom: 6px;
    font-size: 13px;
    color: #475569;
}
</style>
""", unsafe_allow_html=True)


# ── Load model bundle ─────────────────────────────────────────
@st.cache_resource
def load_models():
    with open('models.pkl', 'rb') as f:
        return pickle.load(f)

try:
    bundle = load_models()
    tfidf      = bundle['tfidf']
    dept_model = bundle['dept_model']
    prio_model = bundle['prio_model']
    tag_model  = bundle['tag_model']
    mlb        = bundle['mlb']
    metrics    = bundle['metrics']
    MODELS_OK  = True
except FileNotFoundError:
    MODELS_OK = False


# ── Predict helper ────────────────────────────────────────────
def predict_ticket(body_text, top_k_tags=5):
    vec = tfidf.transform([body_text])

    dept       = dept_model.predict(vec)[0]
    dept_proba = dict(zip(dept_model.classes_, dept_model.predict_proba(vec)[0]))
    top_depts  = sorted(dept_proba.items(), key=lambda x: -x[1])[:4]

    prio       = prio_model.predict(vec)[0]
    prio_proba = dict(zip(prio_model.classes_, prio_model.predict_proba(vec)[0]))

    tag_proba  = tag_model.predict_proba(vec)[0]
    top_idx    = np.argsort(tag_proba)[::-1][:top_k_tags]
    pred_tags  = [mlb.classes_[i] for i in top_idx if tag_proba[i] > 0.2]

    return {
        'department':      dept,
        'dept_confidence': round(dept_proba.get(dept, 0) * 100, 1),
        'top_departments': [(d, round(p * 100, 1)) for d, p in top_depts],
        'priority':        prio,
        'prio_confidence': round(prio_proba.get(prio, 0) * 100, 1),
        'priority_probs':  {k: round(v * 100, 1) for k, v in prio_proba.items()},
        'predicted_tags':  pred_tags,
    }


# ── Sidebar ───────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🎫 IT Ticket AI")
    st.markdown("<span style='color:#94a3b8;font-size:13px'>Logistic Regression · TF-IDF</span>",
                unsafe_allow_html=True)
    st.markdown("---")

    st.markdown("**Paste your ticket description:**")
    ticket_input = st.text_area(
        label="Ticket body",
        height=220,
        placeholder="Describe the issue in detail...\n\nExample:\nOur VPN has been down since 9 AM and no one in the engineering team can connect to the internal servers. This is blocking critical deployments.",
        label_visibility="collapsed"
    )

    analyze_btn = st.button("⚡  Analyze Ticket", use_container_width=True)

    st.markdown("---")
    st.markdown("**Quick examples:**")

    examples = {
        "🔴 Network outage":  "Our entire network is down and no one in the office can connect to the internet or VPN. This is a critical business disruption affecting all employees.",
        "💳 Billing issue":   "My invoice shows duplicate charges for last month. I was billed twice for the same subscription plan. I need an urgent refund processed.",
        "🐛 App crash":       "The application keeps crashing every time I try to export a PDF report. I have tried reinstalling but the bug persists. Error code: 0x8004E.",
        "📋 HR inquiry":      "I need information about the company's remote work policy and how to apply for a flexible working arrangement as a permanent employee.",
    }

    for label, text in examples.items():
        if st.button(label, use_container_width=True, key=label):
            st.session_state["prefill"] = text
            st.rerun()

    # Pre-fill from example click
    if "prefill" in st.session_state:
        ticket_input = st.session_state.pop("prefill")

    st.markdown("---")
    if MODELS_OK:
        st.markdown(f"<span style='color:#4ade80;font-size:12px'>✓ Models loaded · {metrics['n_rows']:,} training rows</span>",
                    unsafe_allow_html=True)
    else:
        st.error("models.pkl not found. Run the notebook first.")


# ── Main area ─────────────────────────────────────────────────
st.markdown("# AI-Based IT Ticket Routing")
st.markdown("<p style='color:#64748b;margin-top:-8px;margin-bottom:1.5rem;'>Automatically predict department routing, priority level, and relevant tags from ticket descriptions.</p>",
            unsafe_allow_html=True)

if not MODELS_OK:
    st.error("⚠️  `models.pkl` not found. Please run the Jupyter notebook first to train and save the models.")
    st.stop()

# ── Model metrics strip ───────────────────────────────────────
c1, c2, c3, c4, c5 = st.columns(5)
cards = [
    (c1, "Dataset",      f"{metrics['n_rows']:,}",          "tickets"),
    (c2, "Departments",  str(metrics['n_departments']),      "classes"),
    (c3, "Dept Acc.",    f"{metrics['dept_acc']}%",          f"F1 {metrics['dept_f1']}"),
    (c4, "Priority Acc.",f"{metrics['prio_acc']}%",          f"F1 {metrics['prio_f1']}"),
    (c5, "Tag F1",       str(metrics['tag_f1_micro']),       "micro score"),
]
for col, label, value, sub in cards:
    with col:
        st.markdown(f"""
        <div class="metric-card">
            <div class="label">{label}</div>
            <div class="value">{value}</div>
            <div class="sub">{sub}</div>
        </div>""", unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# ── Prediction output ─────────────────────────────────────────
if analyze_btn and ticket_input.strip():
    with st.spinner("Analyzing ticket…"):
        time.sleep(0.4)
        result = predict_ticket(ticket_input.strip())

    # Save to history
    if "history" not in st.session_state:
        st.session_state["history"] = []
    st.session_state["history"].insert(0, {
        "text":   ticket_input.strip()[:90] + "…",
        "dept":   result["department"],
        "prio":   result["priority"],
    })
    st.session_state["history"] = st.session_state["history"][:5]

    st.markdown('<div class="section-header">Prediction Results</div>', unsafe_allow_html=True)

    left, right = st.columns([3, 2])

    with left:
        # Department
        conf = result["dept_confidence"]
        conf_cls = "conf-high" if conf >= 70 else ("conf-medium" if conf >= 45 else "conf-low")
        st.markdown(f"""
        <div class="result-card">
            <h4>🏢 Routed Department</h4>
            <div class="result-main">{result['department']}</div>
            <span class="confidence-badge {conf_cls}">{conf}% confidence</span>
        </div>""", unsafe_allow_html=True)

        # Priority
        prio = result["priority"]
        prio_cls = f"prio-{prio}"
        prio_conf = result["prio_confidence"]
        pconf_cls = "conf-high" if prio_conf >= 70 else ("conf-medium" if prio_conf >= 45 else "conf-low")
        st.markdown(f"""
        <div class="result-card">
            <h4>🚨 Priority Level</h4>
            <div style="margin-bottom:10px;">
                <span class="{prio_cls}">{prio.upper()}</span>
            </div>
            <span class="confidence-badge {pconf_cls}">{prio_conf}% confidence</span>
        </div>""", unsafe_allow_html=True)

        # Tags
        tags_html = "".join(f'<span class="tag-chip">{t}</span>' for t in result["predicted_tags"]) if result["predicted_tags"] else "<span style='color:#94a3b8;font-size:13px'>No strong tags detected</span>"
        st.markdown(f"""
        <div class="result-card">
            <h4>🏷️ Predicted Tags</h4>
            <div style="margin-top:4px;">{tags_html}</div>
        </div>""", unsafe_allow_html=True)

    with right:
        # Top departments breakdown
        st.markdown('<div class="section-header">Department Probabilities</div>', unsafe_allow_html=True)
        for dept_name, pct in result["top_departments"]:
            bar_w = int(pct)
            marker = "◆ " if dept_name == result["department"] else ""
            st.markdown(f"""
            <div class="dept-row">
                <span class="dept-name">{marker}{dept_name}</span>
                <div class="dept-bar-track">
                    <div class="dept-bar-fill" style="width:{bar_w}%"></div>
                </div>
                <span class="dept-pct">{pct}%</span>
            </div>""", unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)

        # Priority breakdown
        st.markdown('<div class="section-header">Priority Probabilities</div>', unsafe_allow_html=True)
        prio_colors = {"high": "#E24B4A", "medium": "#EF9F27", "low": "#639922"}
        for p, v in sorted(result["priority_probs"].items(), key=lambda x: -x[1]):
            color = prio_colors.get(p, "#888")
            st.markdown(f"""
            <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px;">
                <span style="font-size:13px;color:#334155;width:70px;">{p.capitalize()}</span>
                <div style="flex:1;height:6px;background:#f1f5f9;border-radius:3px;overflow:hidden;">
                    <div style="width:{v}%;height:100%;background:{color};border-radius:3px;"></div>
                </div>
                <span style="font-size:12px;color:#94a3b8;width:42px;text-align:right;">{v}%</span>
            </div>""", unsafe_allow_html=True)

elif analyze_btn:
    st.warning("Please enter a ticket description in the sidebar.")

else:
    # Placeholder state
    st.markdown("""
    <div style="background:#f8fafc;border:2px dashed #e2e8f0;border-radius:16px;padding:3rem;text-align:center;color:#94a3b8;">
        <div style="font-size:42px;margin-bottom:12px;">🎫</div>
        <div style="font-size:16px;font-weight:500;color:#64748b;margin-bottom:6px;">Paste a ticket in the sidebar</div>
        <div style="font-size:13px;">The model will predict the routing department, priority level, and tags in under a second.</div>
    </div>
    """, unsafe_allow_html=True)


# ── History ───────────────────────────────────────────────────
if st.session_state.get("history"):
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown('<div class="section-header">Recent Predictions</div>', unsafe_allow_html=True)

    prio_colors = {"high": "#fee2e2", "medium": "#fef9c3", "low": "#dcfce7"}
    prio_text   = {"high": "#991b1b",  "medium": "#854d0e",  "low": "#166534"}

    for h in st.session_state["history"]:
        bg   = prio_colors.get(h["prio"], "#f1f5f9")
        tc   = prio_text.get(h["prio"],  "#475569")
        st.markdown(f"""
        <div class="hist-item">
            <span style="font-size:11px;background:{bg};color:{tc};padding:2px 8px;border-radius:99px;font-weight:600;margin-right:8px;">{h['prio'].upper()}</span>
            <span style="color:#4F46E5;font-weight:500;">{h['dept']}</span>
            <span style="color:#94a3b8;margin-left:8px;font-size:12px;">{h['text']}</span>
        </div>""", unsafe_allow_html=True)


# ── Footer ────────────────────────────────────────────────────
st.markdown("<br><br>", unsafe_allow_html=True)
st.markdown("""
<div style="text-align:center;color:#cbd5e1;font-size:12px;border-top:1px solid #f1f5f9;padding-top:1rem;">
    IT Ticket AI · Logistic Regression + TF-IDF · 27,916 training tickets
</div>
""", unsafe_allow_html=True)
